name: Cleaning

on:
  workflow_dispatch:
  schedule:
    - cron: 30 8 */3 * *

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Old Workflow Runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.REPO_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 3
