name: Cleaning

on:
  schedule:
    - cron: 0 22 */3 * *
  workflow_dispatch:
    inputs:
      retain_days:
        description: 'Days-worth of runs to keep for each workflow (workflow runs)'
        required: true
        default: '3'
      keep_minimum_runs:
        description: 'Minimum runs to keep for each workflow (workflow runs)'
        required: true
        default: '6'
      delete_workflow_by_state_pattern:
        description: 'Filter workflows by state: active, deleted, disabled_fork, disabled_inactivity, disabled_manually (workflow runs)'
        required: true
        default: "ALL"
        type: choice
        options:
          - "ALL"
          - active
          - deleted
          - disabled_inactivity
          - disabled_manually
      delete_run_by_conclusion_pattern:
        description: 'Remove runs based on conclusion: action_required, cancelled, failure, skipped, success (workflow runs)'
        required: true
        default: "ALL"
        type: choice
        options:
          - "ALL"
          - "Unsuccessful: action_required,cancelled,failure,skipped"
          - action_required
          - cancelled
          - failure
          - skipped
          - success

env:
  retain_days: ${{ github.event_name == 'workflow_dispatch' && inputs.retain_days || '3' }}
  keep_minimum_runs: ${{ github.event_name == 'workflow_dispatch' && inputs.keep_minimum_runs || '6' }}
  delete_workflow_by_state_pattern: ${{ github.event_name == 'workflow_dispatch' && inputs.delete_workflow_by_state_pattern || 'ALL' }}
  delete_run_by_conclusion_pattern: ${{ github.event_name == 'workflow_dispatch' && inputs.delete_run_by_conclusion_pattern || 'ALL' }}

jobs:
  cleaning:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.REPO_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: ${{ env.retain_days }}
          keep_minimum_runs: ${{ env.keep_minimum_runs }}
          delete_workflow_by_state_pattern: ${{ env.delete_workflow_by_state_pattern }}
          delete_run_by_conclusion_pattern: ${{ env.delete_run_by_conclusion_pattern }}

      - name: Delete older releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 3
          delete_tags: true
          delete_expired_data: 3
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
