name: Fetch Cache

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 */3 * *

env:
  REPO_URL: "https://github.com/openwrt/openwrt"
  REPO_BRANCH: "openwrt-23.05"

jobs:
  fetch_cache:
    name: fetch cache
    runs-on: ubuntu-latest

    steps:
    - name: Show System
      run: |
        lscpu
        free -h
        uname -a

    - name: Set Time Zone
      run: |
        sudo -E timedatectl set-timezone 'Asia/Shanghai'

    - name: Checkout
      uses: actions/checkout@main

    - name: Build System Setup
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt update
        xargs -a dependencies sudo -E apt -y install
        sudo -E systemctl daemon-reload
        sudo -E apt -y autoremove --purge
        sudo -E apt clean
        sudo -E git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'
        sudo -E git config --global core.abbrev auto
        sudo -E git config --global advice.detachedHead false
        df -h

    - name: Clone Source Code
      run: |
        #git clone --single-branch -b "${REPO_BRANCH}" "${REPO_URL}" openwrt
        latest_release="$(curl -s https://github.com/openwrt/openwrt/tags | grep -Eo "v[0-9\.]+\-*r*c*[0-9]*\.tar\.gz" | sed -n '/[2-9][3-9]/p' | sed -n 1p | sed 's/\.tar\.gz//g')"
        git clone --single-branch -b "${latest_release}" https://github.com/openwrt/openwrt openwrt

    - name: Update Feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a && ./scripts/feeds install -a

    - name: Make Defconfig
      run: |
        cd openwrt
        cp -f ../SEED/X86/config.seed .config
        make defconfig

    - name: Generate Cache Mixkey
      run: |
        cd openwrt
        BOARD="$(sed -n 's/^CONFIG_TARGET_BOARD=\"\(.*\)\"/\1/p' ".config")"
        SUBTARGET="$(sed -n 's/^CONFIG_TARGET_SUBTARGET=\"\(.*\)\"/\1/p' ".config")"
        GCC_HASH="$(gcc --version | sha256sum | awk '{print substr($1,1,8)}')"
        LDD_HASH="$(ldd --version | sha256sum | awk '{print substr($1,1,8)}')"
        echo "MIXKEY=${BOARD}-${SUBTARGET}-${GCC_HASH}-${LDD_HASH}" >> "${GITHUB_ENV}"

    - name: Cache
      uses: HiGarfield/cachewrtbuild@main
      with:
        ccache: 'true'
        mixkey: ${{ env.MIXKEY }}
        prefix: ${{ github.workspace }}/openwrt
        skip_saving: 'true'
